#!/bin/bash -e
cmd=cms-nats-sub
eval $(scram unsetenv -sh)
THISDIR=$(dirname $0)
SHARED_ARCH=$(cmsos)
TOOL=$(ls -d ${THISDIR}/../${SHARED_ARCH}_*/cms/cmsmon-tools/*/$cmd 2>/dev/null | sort | tail -1)
[ -z $TOOL ] && >&2 echo "ERROR: Unable to find command '$cmd' for '$SHARED_ARCH' architecture." && exit 1
$TOOL "$@"
