# Image in the registry: registry.cern.ch/cmsmonitoring/grafana-daily-backup
FROM registry.cern.ch/cmsmonitoring/cmsmon-py:4.0.0

# Copy only the specific files you need instead of cloning entire repos
COPY src/ ./
