# --- Builds cmsmon-py docker image ---
name: Build

on:
  push:
    tags:
      - 'drpy-*.*.*'

jobs:
  build-cmsmon-py:
    name: Build cmsmon-py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Get git tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Get cmsmon-py Dockerfile
        run: |
          curl -ksLO https://raw.githubusercontent.com/dmwm/CMSKubernetes/master/docker/cmsmon-py/Dockerfile
      - name: Login to registry.cern.ch
        uses: docker/login-action@v1
        with:
          registry: registry.cern.ch
          username: ${{ secrets.CERN_LOGIN }}
          password: ${{ secrets.CERN_TOKEN }}
      - name: Publish cmsmon-py image to registry.cern.ch
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            PY_VERSION=3.9.12
            CMSMONITORING_TAG=${{ steps.get_tag.outputs.tag }}
          tags: registry.cern.ch/cmsmonitoring/cmsmon-py:${{ steps.get_tag.outputs.tag }}
